### ISSUE TITLE
Updating Elastic UI

### ISSUE THREAD

**Issue by jusa3** [ts4nfdi/terminology-service-suite#102]
Pros:
- usage of new parameters e.g. truncationProps in EuiComboBox (https://github.com/ts4nfdi/terminology-service-suite/issues/98)
- support of consumer apps that use later Eui versions (e.g. NFDI4Health Study Hub)

Cons:
- possible deprecations of functions/parameters - check change logs
- a lot of work to check all widgets after update

**Comment by jusa3** [comment]
The error with the HTML Widgets:
```
Uncaught TypeError: Cannot set properties of undefined (setting 'Symbol(Symbol.toStringTag)')
    at Vsn (terminology-service-suite.min.js:377:17232)
```
Could be solved with https://github.com/ts4nfdi/esbuild-dynamic-import/commit/cca171f0988bb0406106c5f51d380865aec4bd31

**Comment by jusa3** [comment]
The icons are not visible in the HTML Storybook and we get the error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'icon')
    at terminology-service-suite.min.js:374:21172
```
Solved by https://github.com/ts4nfdi/esbuild-dynamic-import/commit/4d38ce3c94c0f75805d2536f19b1ff9b8545ec87
