### ISSUE TITLE
annotationProperty, dataProperty and objectProperty new OLS4 entity types lead to errors

### ISSUE THREAD

**Issue by jusa3** [ts4nfdi/terminology-service-suite#132]
Beside class/term, property and individual there are annotationProperty, dataProperty and objectProperty.

From http://ols4-test.qa.km.k8s.zbmed.de/ols4/api/search?exact=false&obsoletes=false&q=notation&groupField=true&rows=10&start=0
```
  "response": {
    "docs": [
      {
        "iri": "http://www.w3.org/2004/02/skos/core#notation",
        "ontology_name": "atc",
        "ontology_prefix": "ATC",
        "short_form": "notation",
        "description": [
          
        ],
        "label": "notation",
        "obo_id": "notation",
        "type": "dataProperty"
      }
    ],
    "numFound": 1,
    "start": 0
  },
```
and 
```
facet_counts": {
    "facet_fields": {
      "ontologyPreferredPrefix": [
        "atc",
        "1"
      ],
      "isDefiningOntology": [
        "false",
        "1"
      ],
      "ontologyId": [
        "atc",
        "1"
      ],
      "ontologyIri": [
        "atc",
        "1",
        "http",
        "1",
        "ontology",
        "1",
        "purl.bioontology.org",
        "1"
      ],
      "isObsolete": [
        "false",
        "1"
      ],
      "type": [
        "dataproperty",
        "1",
        "entity",
        "1",
        "property",
        "1",
        "annotationproperty",
        "0",
        "class",
        "0",
        "individual",
        "0",
        "objectproperty",
        "0",
        "ontology",
        "0"
      ]
```

but is a property in http://ols4-test.qa.km.k8s.zbmed.de/ols4/api/ontologies/atc/properties?iri=http:%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation 

Leads in the SemLookP app to:
```
No thingType found to pluralize in provided typeArray.
    at pluralizeType (http://localhost:3000/static/js/bundle.js:88931:9)
    at MetadataCompact (http://localhost:3000/static/js/bundle.js:110780:110)
```
and in the SearchResultsListWidget to:
```
query.js:358 Error: Invalid entity type "dataProperty". Must be one of {"term", "class", "property", "individual"}
    at OlsApi.getEntityWithEntityTypeProvided (OlsApi.ts:496:1)
    at OlsApi.getEntityObject (OlsApi.ts:433:1)
    at Object.queryFn (terminology-service-suite/:12:1)
    at Object.fetchFn [as fn] (query.js:300:1)
    at run (retryer.js:95:1)
    at retryer.js:149:1
```

**Comment by jusa3** [comment]
Also caused the error:

```
console.js:288 Error: Entity type could not be correctly inferred.
    at createModelObject (ModelObjectCreator.ts:39:1)
    at OlsApi.getEntityObject (OlsApi.ts:444:1)
    at async OlsApi.buildHierarchyWithIri (OlsApi.ts:641:1)
    at async Object.getNewHierarchy [as queryFn] (HierarchyWidget.tsx:111:1)
```
